package mx.ipn.escom.ScannerComponents;

public enum TipoToken {
    AND,
    CLASS,
    ELSE,
    FALSE,
    BREAK,
    FUNCTION,
    IF,
    NULL,
    OR,
    PRINT,
    RETURN,
    SUPER,
    THIS,
    TRUE,
    VAR,
    WHILE,
    PARENTESIS_IZQUIERDO,
    PARENTESIS_DERECHO,
    CORCHETE_IZQUIERDO,
    CORCHETE_DERECHO,
    LLAVE_IZQUIERDA,
    LLAVE_DERECHA,
    COMA,
    PUNTO,
    PUNTO_Y_COMA,
    SUMA,
    RESTA,
    MULTIPLICACION,
    DIVISION,
    NEGACION,
    DIFERENTE,
    ASIGNAR,
    IGUAL_A,
    MENOR_QUE,
    MENOR_O_IGUAL,
    MAYOR_QUE,
    MAYOR_O_IGUAL,
    IDENTIFICADOR,
    CADENA,
    NUMERO,
    COMENTARIOS,//no se va generar pero es necesario
    EOF
}
